services:
  dozzle:
    image: amir20/dozzle:latest
    security_opt:
      - no-new-privileges:true
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    networks:
      - swag
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: data
        target: /data
volumes:
  data: {}
networks:
  swag:
    external: true
