apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epicgames-fgn-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Ki
  volumeName: "pv-epicgames-freegames-node"
status: {}
