apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-epicgames-freegames-node
spec:
  storageClassName: local-path
  capacity:
    storage: 500Ki
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /path/to/local/volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hostname-of-host
