[services]
[services.firefly-core]
image = "fireflyiii/core:latest"
hostname = "firefly-core"
container_name = "firefly-core"
env_file = "firefly-core.env"
networks = [
  "swag"
]
# ports = [
#   "80:8080"
# ]
depends_on = [
  "firefly-db"
]
restart = "always"
[services.firefly-core.environment]
APP_ENV = "production"
APP_DEBUG = false
SITE_OWNER = "mail@example.com"
APP_KEY = "SomeRandomStringOf32CharsExactly"
DEFAULT_LANGUAGE = "en_US"
DEFAULT_LOCALE = "equal"
TZ = "America/Panama"
TRUSTED_PROXIES = "**"
LOG_CHANNEL = "stack"
APP_LOG_LEVEL = "notice"
AUDIT_LOG_LEVEL = "emergency"
DB_CONNECTION = "mysql"
DB_HOST = "firefly-db"
DB_PORT = "3306"
DB_DATABASE = "firefly-db"
DB_USERNAME = "firefly"
DB_PASSWORD = "same as DB container"
MYSQL_USE_SSL = false
MYSQL_SSL_VERIFY_SERVER_CERT = true
MYSQL_SSL_CAPATH = "/etc/ssl/certs/"
PGSQL_SSL_MODE = "prefer"
PGSQL_SCHEMA = "public"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
COOKIE_PATH = "/"
COOKIE_SECURE = false
COOKIE_SAMESITE = "lax"
MAIL_MAILER = "smtp"
MAIL_HOST = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_FROM = "mail@example.com"
MAIL_USERNAME= "mail@example.com"
MAIL_PASSWORD = ""
MAIL_ENCRYPTION = true
SEND_ERROR_MESSAGE = true
SEND_REPORT_JOURNALS = true
ENABLE_EXTERNAL_MAP = true
ENABLE_EXCHANGE_RATES = false
ENABLE_EXTERNAL_RATES = false
MAP_DEFAULT_LAT = 51.983333
MAP_DEFAULT_LONG = 5.916667
MAP_DEFAULT_ZOOM = 6
VALID_URL_PROTOCOLS= "http,https"
AUTHENTICATION_GUARD = "web"
DISABLE_FRAME_HEADER = false
DISABLE_CSP_HEADER = false
ALLOW_WEBHOOKS = false
STATIC_CRON_TOKEN = "Another32CharValue"
DKR_BUILD_LOCALE = false
DKR_CHECK_SQLITE = true
DKR_RUN_MIGRATION = true
DKR_RUN_UPGRADE = true
DKR_RUN_VERIFY = true
DKR_RUN_REPORT = true
DKR_RUN_PASSPORT_INSTALL = true
APP_NAME = "FireflyIII"
BROADCAST_DRIVER = "log"
QUEUE_DRIVER = "sync"
CACHE_PREFIX = "firefly"
FIREFLY_III_LAYOUT = "v1"
APP_URL = "http://localhost"
[[services.firefly-core.volumes]]
type = "volume"
source = "upload"
target = "/var/www/html/storage/upload"

[services.firefly-db]
image = "mariadb:lts"
container_name = "firefly-db"
hostname = "firefly-db"
restart = "always"
env_file = ".firefly-db.env"
networks = ["swag"]
[services.firefly-db.environment]
MYSQL_RANDOM_ROOT_PASSWORD = "yes"
MYSQL_USER = "firefly"
MYSQL_PASSWORD = "secret_firefly_password"
MYSQL_DATABASE = "firefly-db"
[[services.firefly-db.volumes]]
type = "volume"
source = "data"
target = "/var/lib/mysql"

[services.firefly-importer]
image = "fireflyiii/data-importer:latest"
container_name = "firefly-importer"
hostname = "firefly-importer"
restart = "always"
networks = [
  "swag"
]
# ports = [
#   "81:8080"
# ]
depends_on = [
  "firefly-core"
]
env_file = ".firefly-importer.env"
[services.firefly-importer.environment]
FIREFLY_III_URL= "https://firefly_iii"
VANITY_URL = "https://firefly.domain.name"
USE_CACHE = false
IGNORE_DUPLICATE_ERRORS = false
CONNECTION_TIMEOUT = 10
APP_ENV = "production"
APP_DEBUG = false
LOG_CHANNEL = "stack"
LOG_LEVEL = "notice"
TRUSTED_PROXIES = "**"
TZ = "America/Panama"
ENABLE_MAIL_REPORT = true
EXPECT_SECURE_URL = true
MAIL_MAILER = "smtp"
MAIL_DESTINATION = "mail@example.com"
MAIL_FROM_ADDRESS = "mail@example.com"
MAIL_HOST = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USERNAME= "mail@example.com"
MAIL_PASSWORD = ""
MAIL_ENCRYPTION = true
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = 120
IS_EXTERNAL = false
APP_NAME = "FireflyDataImporter"

[services.firefly-cron]
image = "alpine"
restart = "always"
container_name = "firefly-cron"
command = 'sh -c "echo \"0 3 * * * wget -qO- http://firefly-core:8080/api/v1/cron/STATIC_CRON_TOKENValue\" | crontab - && crond -f -L /dev/stdout"'
networks = ["swag"]

[volumes]
[volumes.upload]
[volumes.data]

[networks]
[networks.swag]
external = true

