stages:
  - deploy

deploy:
  stage: deploy
  image: $GIT_IMAGE
  before_script:
    # Install git
    - apk update && apk add --no-cache git

    # Configure required Git identity
    - git config --global user.name "${FULL_NAME}"
    - git config --global user.email "${EMAIL}"

  script:
    # GitHub remote

    - |
      if git remote | grep -q github; then
        git remote set-url github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
      else
        git remote add github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
      fi
    - git push -u github $CI_COMMIT_BRANCH

    # GitLab remote

    - |
      if git remote | grep -q gitlab; then
        git remote set-url gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
      else
        git remote add gitlab https://gitlab-ci-token:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
      fi
    - git push -u gitlab $CI_COMMIT_BRANCH

    # Cleanup remotes to avoid caching issues
    - git remote remove github || true
    - git remote remove gitlab || true

