stages:
  - deploy

deploy:
  stage: deploy
  image: ${GIT_IMAGE}
  before_script:
    - apk add bash
    - git config --global user.name "${FULL_NAME}"
    - git config --global user.email "${EMAIL}"
    - git checkout ${CI_COMMIT_BRANCH}
  script:
    - git remote add github https://git:${GITHUB_TOKEN}@github.com/${GIT_USER}/${TARGET_REPO}.git ||
      git remote set-url github https://git:${GITHUB_TOKEN}@github.com/${GIT_USER}/${TARGET_REPO}.git
    - git push github ${CI_COMMIT_BRANCH}

    - git remote add gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${TARGET_REPO}.git ||
      git remote set-url gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${TARGET_REPO}.git
    - git push gitlab ${CI_COMMIT_BRANCH}
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
