stages:
  - deploy

deploy:
  stage: deploy
  image: ${GIT_IMAGE}
  before_script:
    - apk update && apk add git
    - git config --global user.name "${FULL_NAME}"
    - git config --global user.email "${EMAIL}"
    - git checkout $CI_COMMIT_BRANCH

  script:
    - git remote add github https://git:${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git ||
      git remote set-url github https://git:${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
    - git push --force github $CI_COMMIT_BRANCH

    - git remote add gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git #||
    # - git remote set-url gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
    - git push --force gitlab $CI_COMMIT_BRANCH
