stages:
  - deploy

deploy:
  stage: deploy
  image: alpine/git:latest
  before_script:
    - git config --global user.name "${GIT_USER_NAME}"
    - git config --global user.email "${GIT_USER_EMAIL}"
    - git checkout ${CI_COMMIT_BRANCH}
  script:
    - git remote add github https://git:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${TARGET_REPO}.git ||
      git remote set-url github https://git:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${TARGET_REPO}.git
    - git push github ${CI_COMMIT_BRANCH}

    - git remote add gitlab https://${CI_USERNAME}:${GITLAB_TOKEN}@gitlab.com/${CI_USERNAME}/${TARGET_REPO}.git ||
      git remote set-url gitlab https://${CI_USERNAME}:${GITLAB_TOKEN}@gitlab.com/${CI_USERNAME}/${TARGET_REPO}.git
    - git push gitlab ${CI_COMMIT_BRANCH}
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
