stages:
  - deploy

deploy:
  stage: deploy
  image: $GIT_IMAGE
  script:
    # Install git
    - apk update && apk add git

    # Configure required variables and settings
    - git config --global user.name "${FULL_NAME}"
    - git config --global user.email "${EMAIL}"
    - git checkout $CI_COMMIT_BRANCH
    - git pull


    # Push to GitHub
    - git remote set-url github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git ||
      git remote add github https://${GITHUB_TOKEN}@github.com/${GIT_USER}/${CI_PROJECT_NAME}.git
    - git push github

    # Push to GitLab
    - git remote set-url gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git ||
      git remote add gitlab https://${GIT_USER}:${GITLAB_TOKEN}@gitlab.com/${GIT_USER}/${CI_PROJECT_NAME}.git
    - git push gitlab

    # Remove remotes to avoid caching issues
    - echo "Starting cleanup..."
    - git remote remove github
    - git remote remove gitlab
    - echo "Cleanup completed."
