stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  script:
    # Install git
    - apk update && apk add git

    # Configure required variables and settings
    - git config --global user.name "${FULL_NAME}"
    - git config --global user.email "${EMAIL}"
    - git checkout $CI_COMMIT_BRANCH
    - git pull


    # Push to GitHub
    - git remote add github https://${GITHUB_TOKEN}@github.com/${USERNAME}/${TARGET_REPO}.git
    - git push github

    # Push to GitLab
    - git remote add gitlab https://${USERNAME}:${GITLAB_TOKEN}@gitlab.com/${USERNAME}/${TARGET_REPO}.git
    - git push gitlab

    # Clean up
    - echo "Starting cleanup..."
    - git remote remove github
    - git remote remove gitlab
    - git config --global --unset user.name
    - git config --global --unset user.email
    - apk del git
    - echo "Cleanup completed."
