[services]
[services.kanboard]
image = "kanboard/kanboard:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "kanboard"
hostname = "kanboard"
networks = [
  "swag"
]
# ports = [
#   "80:80",
#   "443:443"
# ]
restart = "unless-stopped"
[[services.kanboard.volumes]]
type = "volume" 
source = "data"
target = "/var/www/app/data"
[[services.kanboard.volumes]]
type = "volume"
source = "plugins"
target = "/var/www/app/plugins"
[[services.kanboard.volumes]]
type = "volume"
source = "ssl"
target = "/etc/nginx/ssl"
[services.kanboard.environment]
DATABASE_URL = "mysql://kanboard:user-password@db/kanboard"

[services.db]
image = "mariadb:10.9"
container_name = "kanboard-db"
hostname = "kanboard-db"
networks = [
  "swag"
]
restart = "unless-stopped"
command = "--default-authentication-plugin=mysql_native_password"
[[services.db.volumes]]
type = "volume"
source = "db"
target = "/var/lib/mysql"
[services.db.environment]
MYSQL_ROOT_PASSWORD = "root-pw"
MYSQL_DATABASE = "kanboard"
MYSQL_USER = "kanboard"
MYSQL_PASSWORD = "user-password"

[volumes.data]
[volumes.plugins]
[volumes.ssl]
[volumes.db]

[networks.swag]
external = true
