version: "3.9"
services:
  kanboard:
    image: kanboard/kanboard:latest
    security_opt:
      - no-new-privileges:true
    container_name: kanboard
    hostname: kanboard
    networks:
      - kanboard
    restart: unless-stopped
    volumes:
      - type: volume
        source: data
        target: /var/www/app/data
      - type: volume
        source: plugins
        target: /var/www/app/plugins
      - type: volume
        source: ssl
        target: /etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:user-password@db/kanboard
  db:
    image: mariadb:10.9
    container_name: kanboard-db
    networks:
      - kanboard
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: user-password
volumes:
  data: {}
  plugins: {}
  ssl: {}
  db: {}
networks:
  kanboard:
    external: true
