version = "3.9"

[services.container]
image = "container_img_address"
container_name = "container"
# hostname = "container"
# domainname = "toplevel.domain"
ports = [
  "80:80"
]
restart = "unless-stopped"
# networks = [
#   "customnetwork"
# ]
[[services.container.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.container.volumes]]
type = "volume"
source = "data"
target = "/data"

# [networks.customnetwork]
# external = true