version = "3.9"

[services.ntfy]
image = "binwiederhier/ntfy"
security_opt = [ "no-new-privileges:true" ]
container_name = "ntfy"
hostname = "ntfy"
command = "serve"
networks = [
  "ntfy"
]
# ports = [
#   "8083:80"
# ]
restart = "unless-stopped"
[[services.ntfy.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.ntfy.volumes]]
type = "volume"
source = "data"
target = "/etc/ntfy"
[[services.ntfy.volumes]]
type = "volume"
source = "cache"
target = "/var/cache/ntfy"

[volumes]
[volumes.data]
[volumes.cache]

[networks.ntfy]
external = true
