apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: "pv-speedtest-tracker-db"
status: {}
