apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-speedtest-tracker-data
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/kubernetes/pv/speedtest-tracker-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - olympos
