apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-speedtest-tracker-db
spec:
  storageClassName: local-path
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/kubernetes/pv/speedtest-tracker-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - olympos
