[services.broker]
image = "docker.io/library/redis:8"
security_opt = [ "no-new-privileges:true" ]
container_name = "paperless-redis"
hostname = "paperless-redis"
restart = "unless-stopped"
networks = [ "swag" ]
[[services.broker.volumes]]
type = "volume"
source = "redis"
target = "/data"
[services.db]
image = "docker.io/library/mariadb:11"
security_opt = [ "no-new-privileges:true" ]
container_name = "paperless-db"
hostname = "paperless-db"
restart = "unless-stopped"
networks = [ "swag" ]
[services.db.environment]
MARIADB_HOST = "paperless"
MARIADB_DATABASE = "paperless"
MARIADB_USER = "paperless"
MARIADB_PASSWORD = "paperless"
MARIADB_ROOT_PASSWORD = "paperless" 
PAPERLESS_ALLOWED_HOSTS = "paperless.domain.com"
PAPERLESS_CSRF_TRUSTED_ORIGINS = "https://paperless.domain.com"
[[services.db.volumes]]
type = "volume"
source = "db"
target = "/var/lib/mysql"
[services.webserver]
image = "ghcr.io/paperless-ngx/paperless-ngx:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "paperless"
hostname = "paperless"
restart = "unless-stopped"
networks = [ "swag" ]
depends_on = ["db", "broker", "gotenberg", "tika"]
# ports = ["8000:8000"]
# env_file = "docker-compose.env"
[services.webserver.environment]
PAPERLESS_REDIS = "redis://broker:6379"
PAPERLESS_DBENGINE = "mariadb"
PAPERLESS_DBHOST = "db"
PAPERLESS_DBUSER = "paperless"
PAPERLESS_DBPASS = "paperless"
PAPERLESS_DBPORT = 3306
PAPERLESS_TIKA_ENABLED = 1
PAPERLESS_TIKA_GOTENBERG_ENDPOINT = "http://gotenberg:3000"
PAPERLESS_TIKA_ENDPOINT = "http://tika:9998"
[[services.webserver.volumes]]
type = "volume"
source = "data"
target = "/usr/src/paperless/data"
[[services.webserver.volumes]]
type = "volume"
source = "media"
target = "/usr/src/paperless/media"
[[services.webserver.volumes]]
type = "volume"
source = "export"
target = "/usr/src/paperless/export"
[[services.webserver.volumes]]
type = "volume"
source = "consume"
target = "/usr/src/paperless/consume"
[services.gotenberg]
image = "docker.io/gotenberg/gotenberg:8.20"
security_opt = [ "no-new-privileges:true" ]
container_name = "gotenberg"
hostname = "gotenberg"
restart = "unless-stopped"
command = ["gotenberg", "--chromium-disable-javascript=true", "--chromium-allow-list=file:///tmp/.*"]
networks = [ "swag" ]
[services.tika]
image = "docker.io/apache/tika:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "tika"
hostname = "tika"
restart = "unless-stopped"
networks = [ "swag" ]

[volumes.data]
[volumes.media]
[volumes.db]
[volumes.redis]
[volumes.consume]
[volumes.export]

[networks.swag]
external = true
