[services.epicgames-freegames-node]
image = "ghcr.io/claabs/epicgames-freegames-node:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "epicgames-freegames-node"
hostname = "epicgames-freegames-node"
domainname = "domain.name"
networks = [
  "epicgames_freegames_node"
]
# ports = [
#   "3000:3000"
# ]
restart = "unless-stopped"
[services.epicgames-freegames-node.environment]
TZ = "America/Panama"
[[services.epicgames-freegames-node.volumes]]
type = "volume" 
source = "data"
target = "/usr/app/config"
[services.epicgames-freegames-node.deploy.resources.limits]
memory = "1g"

[volumes.data]
[networks.epicgames_freegames_node]
external = true
