version = "3.8"

[services.hbbs]
image = "rustdesk/rustdesk-server:latest"
container_name = "hbbs"
command = "hbbs -r example.domain.com:21117"
restart = "unless-stopped"
ports = [
  "21115:21115",
  "21116:21116",
  "21116:21116/udp",
  "21118:21118"
]
networks = [
  "net"
]
depends_on = [
  "hbbr"
]
volumes = [
    "./hbbs:/root"
]

[services.hbbr]
image = "rustdesk/rustdesk-server:latest"
container_name = "hbbr"
command = "hbbr"
restart = "unless-stopped"
networks = [
    "net"
]
ports = [
  "21117:21117",
  "21119:21119"
]
volumes = [
    "./hbbr:/root"
]

[networks.net]
external = false
