services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    security_opt:
      - no-new-privileges:true
    container_name: hbbs
    hostname: hbbs
    command: hbbs -r example.domain.com:21117
    restart: unless-stopped
    networks:
      - rustdesk
    depends_on:
      - hbbr
    volumes:
      - type: volume
        source: data
        target: /root
  hbbr:
    image: rustdesk/rustdesk-server:latest
    security_opt:
      - no-new-privileges:true
    container_name: hbbr
    hostname: hbbr
    command: hbbr
    restart: unless-stopped
    networks:
      - rustdesk
    volumes:
      - type: volume
        source: data
        target: /root
networks:
  rustdesk:
    external: true
volumes:
  data: {}
