# Traefik STATIC configuration TOML file.
version = "3.4"

[services.traefik]
image = "traefik:latest"
container_name = "traefik"
network_mode = "host"
restart = "unless-stopped"
command = [
  "--api.insecure=true",
  "--providers.docker=true",
  "--providers.docker.exposedbydefault=false",
  "--providers.file.directory=/etc/traefik/conf",
  "--providers.file.watch=true",
  "--entrypoints.web.address=:80",
  "--entryPoints.web.http.redirections.entryPoint.to=websecure",
  "--entryPoints.web.http.redirections.entryPoint.scheme=https",
  "--entrypoints.websecure.address=:443",
  "--log.level=info",
  "--serversTransport.insecureSkipVerify=true",
#
  "--certificatesresolvers.cloudflare.acme.dnschallenge=true",
  "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare",
  "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53",
  "--certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory",
  "--certificatesresolvers.cloudflare.acme.email=email@example.com",
  "--certificatesresolvers.cloudflare.acme.KeyType=EC256",
  "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json",
#
  "--certificatesresolvers.cloudflare-staging.acme.dnschallenge=true",
  "--certificatesresolvers.cloudflare-staging.acme.dnschallenge.provider=cloudflare",
  "--certificatesresolvers.cloudflare-staging.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53",
  "--certificatesresolvers.cloudflare-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory",
  "--certificatesresolvers.cloudflare-staging.acme.email=email@example.com",
  "--certificatesresolvers.cloudflare-staging.acme.KeyType=EC256",
  "--certificatesresolvers.cloudflare-staging.acme.storage=/letsencrypt/acme.json",
#
  "--certificatesresolvers.alpn.acme.tlsChallenge=true",
  "--certificatesresolvers.alpn.acme.caserver=https://acme-v02.api.letsencrypt.org/directory",
  "--certificatesresolvers.alpn.acme.email=email@example.com",
  "--certificatesresolvers.alpn.acme.KeyType=EC256",
  "--certificatesresolvers.alpn.acme.storage=/letsencrypt/acme.json",
#
  "--certificatesresolvers.alpn-staging.acme.tlsChallenge=true",
  "--certificatesresolvers.alpn-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory",
  "--certificatesresolvers.alpn-staging.acme.email=email@example.com",
  "--certificatesresolvers.alpn-staging.acme.KeyType=EC256",
  "--certificatesresolvers.alpn-staging.acme.storage=/letsencrypt/acme.json"
]
environment = [
  "CLOUDFLARE_EMAIL=email@example.com",
  "CLOUDFLARE_API_KEY=INSERT_CF_API_KEY_HERE" # Replace with your CF API key.
]
[[services.traefik.volumes]]
type = "volume"
source = "letsencrypt"
target = "/letsencrypt"
[[services.traefik.volumes]]
type = "bind"
source = "/var/run/docker.sock"
target = "/var/run/docker.sock"
read_only = true
[[services.traefik.volumes]]
type = "volume"
source = "conf"
target = "/etc/traefik/conf"
read_only = true
[[services.traefik.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true

[volumes.letsencrypt]
[volumes.conf]