version: "3"
services:
  reverse-proxy:
    image: traefik:v2.8
    command:
      - --providers.docker
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    networks:
      - lan
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.local`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=web,websecure
networks:
  lan:
    external: true
