version = "3.9"

[services.dockge]
image = "louislam/dockge:latest"
container_name = "dockge"
# hostname = "container"
# domainname = "toplevel.domain"
ports = [
  "5001:5001"
]
restart = "unless-stopped"
# networks = [
#   "customnetwork"
# ]
[services.dockge.environment]
DOCKGE_STACKS_DIR = "/opt/stacks"
[[services.dockge.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.dockge.volumes]]
type = "bind"
source = "/opt/stacks"
target = "/opt/stacks"
[[services.dockge.volumes]]
type = "bind"
source = "/var/run/docker.sock"
target = "/var/run/docker.sock"
[[services.dockge.volumes]]
type = "volume"
source = "data"
target = "/app/data"

[volumes.data]

# [networks.customnetwork]
# external = true
