version: "3.9"
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    ports:
      - 5001:5001
    restart: unless-stopped
    environment:
      DOCKGE_STACKS_DIR: /opt/stacks
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /opt/stacks
        target: /opt/stacks
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: data
        target: /app/data
volumes:
  data: {}
