version: "3.9"
services:
  caddy:
    container_name: caddy
    image: caddy:latest
    networks:
      - caddy_net
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - type: volume
        source: caddy_etc
        target: /etc/caddy
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
  pihole-dns:
    depends_on:
      - caddy
    hostname: pihole-dns
    container_name: pihole-dns
    image: pihole/pihole:latest
    networks:
      - caddy_net
    ports:
      - 8081:80/tcp
      - 53:53/udp
      - 53:53/tcp
      - 853:853/tcp
    restart: unless-stopped
    environment:
      TZ: America/Panama
      WEBPASSWORD: password
    volumes:
      - type: volume
        source: pihole_etc
        target: /etc/pihole
      - type: volume
        source: dnmasq_etc
        target: /etc/dnsmasq.d
      - type: volume
        source: lighttpd_etc
        target: /etc/lighttpd/external.conf
networks:
  caddy_net:
    driver: bridge
    name: caddy_net
volumes:
  caddy_etc: {}
  caddy_data: {}
  caddy_config: {}
  pihole_etc: {}
  dnmasq_etc: {}
  lighttpd_etc: {}
