services:
  wireguard:
    image: linuxserver/wireguard:latest
    security_opt:
      - no-new-privileges:true
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    volumes:
      - type: volume
        source: data
        target: /config
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Panama
      SERVERURL: domain.name
      SERVERPORT: 51820
      PEERS: 7
      PEERDNS: 1.1.1.1
      INTERNAL_SUBNET: 10.13.13.0/24
volumes:
  data: {}
