services:
  openproject:
    image: openproject/openproject:14
    security_opt:
      - no-new-privileges:true
    container_name: openproject
    hostname: openproject
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - swag
    environment:
      OPENPROJECT_SECRET_KEY_BASE: ""
      OPENPROJECT_HOST__NAME: domain.name:80
      OPENPROJECT_HTTPS: true
      OPENPROJECT_DEFAULT__LANGUAGE: en
    volumes:
      - type: volume
        source: pgdata
        target: /var/openproject/pgdata
      - type: volume
        source: assets
        target: /var/openproject/assets
volumes:
  pgdata: {}
  assets: {}
networks:
  swag:
    external: true
