version: "3"
services:
  cfddns:
    image: cfddns:latest
    container_name: cfddns
    hostname: cfddns
    restart: unless-stopped
    volumes:
      - type: volume
        source: data
        target: /config
volumes:
  data: {}
