version: "3.9"
services:
  games-db:
    image: mariadb:latest
    container_name: games-db
    hostname: games-db
    restart: unless-stopped
    networks:
      - games-db
    environment:
      PUID: 1000
      PGID: 1000
      MARIADB_DATABASE: games_db
      MARIADB_USER: username
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: volume
        source: data
        target: /var/lib/mysql
volumes:
  data: {}
networks:
  games-db:
    external: true
