version = "3.9"

[services]
[services.uptime-kuma]
image = "louislam/uptime-kuma:latest"
container_name = "uptime-kuma"
hostname = "uptime-kuma"
restart = "always"
# ports = ["3001:3001"]
networks = [
  "uptime_kuma",
  "npm",
  "wireguard"
]
[[services.uptime-kuma.volumes]]
type = "volume"
source = "data"
target = "/app/data"
[[services.uptime-kuma.volumes]]
type = "bind"
source = "/var/run/docker.sock"
target = "/var/run/docker.sock"
[volumes.data]

[networks]
[networks.uptime_kuma]
external = true
[networks.npm]
external = true
[networks.wireguard]
external = true

