version: "3.9"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
      - 3001:3001
    volumes:
      - type: volume
        source: uptime-kuma
        target: /app/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  uptime-kuma: {}
networks: {}
