version: "3.9"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    hostname: uptime-kuma
    restart: always
    networks:
      - uptime_kuma
      - npm
      - wireguard
    volumes:
      - type: volume
        source: data
        target: /app/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  data: {}
networks:
  uptime_kuma:
    external: true
  npm:
    external: true
  wireguard:
    external: true
