# Docker compose version
version = '3'

[services.pihole]
  container_name = "pihole"
  image = "pihole/pihole:latest"
  # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
  ports = [
    "53:53/tcp",
    "53:53/udp",
    "67:67/udp",
    "8001:80/tcp"
  ]
  dns = [
    "127.0.0.1", # local host
    "149.112.112.112", # Quad9
    "9.9.9.9", # Quad9
    "1.1.1.1", # Cloudflare
    "8.8.8.8" # Google
  ]
  volumes = [
    "./etc-pihole:/etc/pihole",
    "./etc-dnsmasq.d:/etc/dnsmasq.d"
  ]
  cap_add = [
    "NET_ADMIN"
  ]
  restart = "unless-stopped"
  # Dependencies for Pi-hole configuration.
[services.pihole.environment]
  TZ = "America/Panama"
  WEBPASSWORD = "" # Add password in production environment.
