services:
  jupyterhub:
    image: quay.io/jupyterhub/jupyterhub
    security_opt:
      - no-new-privileges:true
    container_name: jupyterhub
    hostname: jupyterhub
    networks:
      - jupyterhub
    command: jupyterhub
    environment:
      JPY_COOKIE_SECRET: CookieSecretKey
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: volume
        source: data
        target: /usr/local/share/jupyterhub
      - type: volume
        source: config
        target: /etc/jupyterhub
      - type: volume
        source: log
        target: /var/log
      - type: volume
        source: userdata
        target: /home
  jupyter_installer:
    image: quay.io/jupyterhub/jupyterhub
    security_opt:
      - no-new-privileges:true
    container_name: jupyter_installer
    network_mode: none
    command: pip3 install jupyter
    depends_on:
      - jupyterhub
volumes:
  data: {}
  config: {}
  log: {}
  home: {}
networks:
  jupyterhub:
    external: true
