[services.registry]
image = "registry:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "registry"
hostname = "registry"
# ports = [
#   "5000:5000"
# ]
networks = [ "registry_server" ]
restart = "always"
[[services.registry.volumes]]
type = "volume"
source = "data"
target = "/var/lib/registry"
[services.registry.environment]
REGISTRY_STORAGE_DELETE_ENABLED = true
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin = "[https://registry-ui.domain.name]"
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods = "[HEAD,GET,OPTIONS,DELETE]"
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials = "[true]"
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers = "[Authorization,Accept,Cache-Control]"
REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers = "[Docker-Content-Digest]"

[services.registry-ui]
image = "joxit/docker-registry-ui:main"
security_opt = [ "no-new-privileges:true" ]
container_name = "registry-ui"
hostname = "registry-ui"
# ports = [ "80:80" ]
networks = [ "registry_server" ]
[services.registry-ui.environment]
SINGLE_REGISTRY = true
REGISTRY_TITLE = "Docker Registry UI"
DELETE_IMAGES = true
SHOW_CONTENT_DIGEST = true
NGINX_PROXY_PASS_URL = "http://registry:5000"
SHOW_CATALOG_NB_TAGS = true
CATALOG_MIN_BRANCHES = 1
CATALOG_MAX_BRANCHES = 1
TAGLIST_PAGE_SIZE = 100
REGISTRY_SECURED = false
CATALOG_ELEMENTS_LIMIT = 1000

[volumes.data]
[networks.registry_server]
external = true
