version = "3.3"

[services.registry]
image = "registry:latest"
container_name = "registry"
ports = [
  "5000:5000"
]
restart = "always"
[[services.registry.volumes]]
type = "volume"
source = "data"
target = "/var/lib/registry"
[services.registry.environment]
REGISTRY_STORAGE_DELETE_ENABLED = true

[volumes.data]
