[services]
[services.immich-server]
image = "ghcr.io/immich-app/immich-server:release"
security_opt = [ "no-new-privileges:true" ]
container_name = "immich-server"
hostname = "immich-server"
env_file = [ ".env" ]
networks = [ "swag" ]
# ports = ["3001:3001"]
depends_on = [ "redis", "database" ]
labels = ["com.centurylinklabs.watchtower.enable=false"]
restart = "always"
[[services.immich-server.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.immich-server.volumes]]
type = "volume"
source = "upload"
target = "/usr/src/app/upload"
[services.immich-machine-learning]
container_name = "immich-machine-learning"
hostname = "immich-machine-learning"
image = "ghcr.io/immich-app/immich-machine-learning:release"
security_opt = [ "no-new-privileges:true" ]
env_file = [ ".env" ]
labels = ["com.centurylinklabs.watchtower.enable=false"]
restart = "always"
[[services.immich-machine-learning.volumes]]
type = "volume"
source = "model-cache"
target = "/usr/src/app/upload"
[services.redis]
image = "registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672"
security_opt = [ "no-new-privileges:true" ]
container_name = "redis"
hostname = "redis"
networks = [ "swag" ]
labels = ["com.centurylinklabs.watchtower.enable=false"]
restart = "always"
[services.database]
image = "ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0"
security_opt = [ "no-new-privileges:true" ]
container_name = "immich-database"
hostname = "immich-database"
networks = [ "swag" ]
labels = ["com.centurylinklabs.watchtower.enable=false"]
restart = "always"
[services.database.environment]
POSTGRES_PASSWORD = "${DB_PASSWORD}"
POSTGRES_USER = "${DB_USERNAME}"
POSTGRES_DB = "${DB_DATABASE_NAME}"
POSTGRES_INITDB_ARGS = "--data-checksums"
[[services.database.volumes]]
type = "volume"
source = "postgres"
target = "/var/lib/postgresql/data"

[volumes.upload]
[volumes.model-cache]
[volumes.postgres]

[networks.swag]
external = true
