version = "3.9"

[services]
[services.gitlab]
image = "gitlab/gitlab-ce:latest"
hostname = "gitlab"
networks = [ "gitlab" ]
# ports = [
#   "7443:443",
#   "2222:22",
#   "8085:80"
# ]
container_name = "gitlab"
restart = "always"
shm_size = "256m"
[[services.gitlab.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.gitlab.volumes]]
type = "volume"
source = "config"
target = "/etc/gitlab"
[[services.gitlab.volumes]]
type = "volume"
source = "logs"
target = "/var/log/gitlab"
[[services.gitlab.volumes]]
type = "volume"
source = "data"
target = "/var/opt/gitlab"

[volumes.config]
[volumes.data]
[volumes.logs]

[networks.gitlab]
external = true
