version: "3.9"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    ports:
      - 7443:443
      - "2222:22"
      - 8085:80
    container_name: gitlab
    restart: always
    shm_size: 256m
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: volume
        source: config
        target: /etc/gitlab
      - type: volume
        source: logs
        target: /var/log/gitlab
      - type: volume
        source: data
        target: /var/opt/gitlab
volumes:
  config: {}
  data: {}
  logs: {}
networks: {}
