[services.nginx-proxy-manager]
image = "jc21/nginx-proxy-manager:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "nginx-proxy-manager"
hostname = "nginx-proxy-manager"
ports = [
  "80:80",
  "81:81",
  "443:443",
  "21115:21115",
  "21116:21116",
  "21116:21116/udp",
  "21117:21117",
  "21118:21118",
  "21119:21119",
  "25565:25565",
  "51820:51820",
]
restart = "unless-stopped"
networks = [
  "npm",
  "devrod",
  "dockge",
  "epicgames_freegames_node",
  "firefly_iii",
  "gitlab",
  "immich",
  "jupyterhub",
  "kanboard",
  "logseq",
  "ntfy",
  "passbolt",
  "phpmyadmin",
  "portainer",
  "rustdesk",
  "speedtest_tracker",
  "spigot_minecraft",
  "vaultwarden",
  "wireguard"
]
[[services.nginx-proxy-manager.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.nginx-proxy-manager.volumes]]
type = "volume"
source = "data"
target = "/data"
[[services.nginx-proxy-manager.volumes]]
type = "volume"
source = "letsencrypt"
target = "/etc/letsencrypt"
[[services.nginx-proxy-manager.volumes]]
type = "bind"
source = "/etc/hosts"
target = "/etc/hosts"

[volumes]
[volumes.data]
[volumes.letsencrypt]

[networks.npm]
external = true
[networks.devrod]
external = true
[networks.dockge]
external = true
[networks.epicgames_freegames_node]
external = true
[networks.firefly_iii]
external = true
[networks.gitlab]
external = true
[networks.immich]
external = true
[networks.jupyterhub]
external = true
[networks.kanboard]
external = true
[networks.logseq]
external = true
[networks.ntfy]
external = true
[networks.passbolt]
external = true
[networks.phpmyadmin]
external = true
[networks.portainer]
external = true
[networks.rustdesk]
external = true
[networks.speedtest_tracker]
external = true
[networks.spigot_minecraft]
external = true
[networks.vaultwarden]
external = true
[networks.wireguard]
external = true
