version = "3.9"

[services.nginx_proxy_manager]
image = "jc21/nginx-proxy-manager:latest"
container_name = "nginx_proxy_manager"
hostname = "nginx_proxy_manager"
# domainname = "toplevel.domain"
ports = [
  "80:80",
  "81:81",
  "443:443"
]
restart = "unless-stopped"
# networks = [
#   "customnetwork"
# ]
[[services.nginx_proxy_manager.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.nginx_proxy_manager.volumes]]
type = "volume"
source = "data"
target = "/data"
[[services.nginx_proxy_manager.volumes]]
type = "volume"
source = "letsencrypt"
target = "/etc/letsencrypt"
[[services.nginx_proxy_manager.volumes]]
type = "bind"
source = "/etc/hosts"
target = "/etc/hosts"

[volumes]
[volumes.data]
[volumes.letsencrypt]
# [networks.customnetwork]
# external = true
