services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    security_opt:
      - no-new-privileges:true
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
      - 25565:25565
      - 51820:51820
    restart: unless-stopped
    networks:
      - npm
      - devrod
      - dockge
      - epicgames_freegames_node
      - firefly_iii
      - gitlab
      - immich
      - jupyterhub
      - kanboard
      - logseq
      - ntfy
      - passbolt
      - phpmyadmin
      - portainer
      - rustdesk
      - speedtest_tracker
      - spigot_minecraft
      - vaultwarden
      - wireguard
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: volume
        source: data
        target: /data
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /etc/hosts
        target: /etc/hosts
volumes:
  data: {}
  letsencrypt: {}
networks:
  npm:
    external: true
  devrod:
    external: true
  dockge:
    external: true
  epicgames_freegames_node:
    external: true
  firefly_iii:
    external: true
  gitlab:
    external: true
  immich:
    external: true
  jupyterhub:
    external: true
  kanboard:
    external: true
  logseq:
    external: true
  ntfy:
    external: true
  passbolt:
    external: true
  phpmyadmin:
    external: true
  portainer:
    external: true
  rustdesk:
    external: true
  speedtest_tracker:
    external: true
  spigot_minecraft:
    external: true
  vaultwarden:
    external: true
  wireguard:
    external: true
