# Docker compose version
version = '3'

[services.portainer]
  container_name = "portainer"
  hostname = "portainer"
  image = "portainer/portainer-ce:latest"
  ports = [
    "8000:8000",
    "9443:9443"
  ]
  restart = "always"
  volumes = [
    "/var/run/docker.sock:/var/run/docker.sock",
    "portainer_data:/data",
  ]
