[services.portainer]
  image = "ngxson/portainer-ce-without-annoying:latest"
  container_name = "portainer"
  restart = "unless-stopped"
  security_opt = [
    "no-new-privileges:true"
  ]
  networks = [
    "swag"
  ]
[[services.portainer.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.portainer.volumes]]
type = "bind"
source = "/var/run/docker.sock"
target = "/var/run/docker.sock"
read_only = true
[[services.portainer.volumes]]
type = "volume"
source = "data"
target = "/data"
[networks.swag]
  external = true
[volumes.data]
