version = "3.9"

[services.phpmyadmin]
image = "phpmyadmin"
security_opt = [ "no-new-privileges:true" ]
container_name = "phpmyadmin"
hostname = "phpmyadmin"
domainname = "domain.name"
networks = [
  "games_db",
  "kanboard",
  "speedtest_tracker",
  "phpmyadmin"
]
# ports = [
#   "8082:80"
# ]
restart = "unless-stopped"
[services.phpmyadmin.environment]
PMA_ARBITRARY = 1
[[services.phpmyadmin.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true

[networks.games_db]
external = true
[networks.kanboard]
external = true
[networks.speedtest_tracker]
external = true
[networks.phpmyadmin]
external = true
