version: "3.9"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8082:80
    restart: unless-stopped
    networks:
      - network
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
networks:
  network:
    external: false
