[services]
[services.stirling-pdf]
image = "frooodle/s-pdf:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "stirling-pdf"
hostname = "stirling-pdf"
# ports = ["8080:8080"]
networks = [
  "swag"
]
restart = "unless-stopped"
[services.stirling-pdf.environment]
DOCKER_ENABLE_SECURITY = false
INSTALL_BOOK_AND_ADVANCED_HTML_OPS = false
LANGS = "en_US"
[[services.stirling-pdf.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime" 
read_only = true
[[services.stirling-pdf.volumes]]
type = "volume"
source = "logs"
target = "/logs"
# [[services.stirling-pdf.volumes]]
# type = "volume"
# source = "trainingData"
# target = "/usr/share/tessdata"
# [[services.stirling-pdf.volumes]]
# type = "volume"
# source = "config"
# target = "/configs"

[volumes.logs]
# [volumes.trainingData]
# [volumes.config]

[networks.swag]
external = true
