services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    security_opt:
      - no-new-privileges:true
    container_name: stirling-pdf
    hostname: stirling-pdf
    networks:
      - stirling_pdf
    restart: unless-stopped
    environment:
      DOCKER_ENABLE_SECURITY: false
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en_US
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: volume
        source: logs
        target: /logs
volumes:
  logs: {}
networks:
  stirling_pdf:
    external: true
