version: "3.9"
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    security_opt:
      - no-new-privileges:true
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    networks:
      - speedtest_tracker
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedy
      DB_PASSWORD: password
      APP_KEY: ""
    volumes:
      - type: volume
        source: data
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
  db:
    image: mariadb:10
    security_opt:
      - no-new-privileges:true
    container_name: speedtest-db
    networks:
      - speedtest_tracker
    restart: always
    environment:
      MARIADB_DATABASE: speedtest_tracker
      MARIADB_USER: speedy
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
volumes:
  data: {}
  db: {}
networks:
  speedtest_tracker:
    external: true
