version: "3.8"
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - 8444:443
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedy
      DB_PASSWORD: password
    volumes:
      - type: volume
        source: data
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
  db:
    image: mariadb:10
    container_name: speedtest-db
    restart: always
    environment:
      MARIADB_DATABASE: speedtest_tracker
      MARIADB_USER: speedy
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
volumes:
  data: {}
  db: {}
