services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    security_opt:
      - no-new-privileges:true
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    networks:
      - swag
    restart: always
    depends_on:
      - db
    environment:
      PUID: 1000
      PGID: 1000
      DISPLAY_TIMEZONE: America/Panama
      SPEEDTEST_SCHEDULE: '*/30 * * * *'
      SPEEDTEST_SERVERS: ""
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: speedtest_tracker
      DB_USERNAME: speedy
      DB_PASSWORD: password
      APP_KEY: ""
    volumes:
      - type: volume
        source: data
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
  db:
    image: mariadb:10
    security_opt:
      - no-new-privileges:true
    container_name: speedtest-db
    hostname: speedtest-db
    networks:
      - swag
    restart: always
    environment:
      MARIADB_DATABASE: speedtest_tracker
      MARIADB_USER: speedy
      MARIADB_PASSWORD: password
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
volumes:
  data: {}
  db: {}
networks:
  swag:
    external: true
