apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: cloudflare-ddns
  name: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudflare-ddns
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: cloudflare-ddns
    spec:
      containers:
        - image: favonia/cloudflare-ddns:latest
          name: cloudflare-ddns
          envFrom:
            - configMapRef:
                name: cloudflare-ddns-config
          resources: {}
      restartPolicy: Always
status: {}
