[services.minecraft]
image = "itzg/minecraft-server"
container_name = "spigot_minecraft"
hostname = "spigot_minecraft"
ports = [
  "25565:25565"
]
restart = "unless-stopped"
[services.minecraft.environment]
EULA = true
MEMORY = "4G"
TYPE = "SPIGOT"
[[services.minecraft.volumes]]
type = "volume"
source = "data"
target = "/data"

[volumes.data]
