version = "3.8"

[services.minecraft]
image = "itzg/minecraft-server"
container_name = "spigot_minecraft"
hostname = "spigot_minecraft"
networks = ["spigot_minecraft"]
ports = [
  "25565:25565"
]
[services.minecraft.environment]
EULA = true
MEMORY = "6G"
TYPE = "SPIGOT"
# Spiget resource references:
# SkinRestorer: 2124
# MinePacks: 19286
# LuckPerms: 28140
# SmoothTimber: 39965
# ChestSort: 59773
# RoseStacker: 82729
# Inventory Rollback Plus: 85811
# GPSPathfinder: 104961 X
# External resource references:
# CoreProtect 8631
SPIGET_RESOURCES = "2124,19286,28140,39965,59773,82729,85811"
[[services.minecraft.volumes]]
type = "volume"
source = "data"
target = "/data"

[volumes]
[volumes.data]

[networks]
[networks.spigot_minecraft]
external = false