version = "3.9"

[services.minecraft]
image = "itzg/minecraft-server"
container_name = "spigot-minecraft"
hostname = "spigot-minecraft"
networks = [
  "spigot_minecraft",
  "games-db"
]
# ports = [
#   "25565:25565",
#   "8081:8080" # For Pl3xmap
# ]
restart = "unless-stopped"
[services.minecraft.environment]
EULA = true
MEMORY = "6G"
TYPE = "SPIGOT"
VERSION = "1.19.4"
TZ = "America/Panama"
# Spiget resource references:
# SkinRestorer: 2124
# MinePacks: 19286
# LuckPerms: 28140
# Elevators: 34229
# SmoothTimber: 39965
# ChestSort: 59773
# Criticals: 78906
# RoseStacker: 82729
# RHLeafDecay: 83581
# Inventory Rollback Plus: 85811
# GPSPathfinder: 104961 X
# External resource references (Manual installation):
# ProtocolLib: 1997
# CoreProtect 8631
# InteractionVisualizer: 77050
# Pl3xmap: 109697 (default requires exposing port 8080)
SPIGET_RESOURCES = "2124,19286,28140,34229,39965,59773,78906,82729,83581,85811"
[[services.minecraft.volumes]]
type = "volume"
source = "data"
target = "/data"
[[services.minecraft.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true

[volumes]
[volumes.data]

[networks]
[networks.spigot_minecraft]
external = true
[networks.games_db]
external = true
