version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: spigot_minecraft
    hostname: spigot_minecraft
    networks:
      - spigot_minecraft
    ports:
      - 25565:25565
    environment:
      EULA: true
      MEMORY: 6G
      TYPE: SPIGOT
      SPIGET_RESOURCES: 2124,19286,28140,39965,59773,82729,85811
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data: {}
networks:
  spigot_minecraft:
    external: false
