version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: spigot_minecraft
    ports:
      - 25565:25565
    environment:
      EULA: true
      MEMORY: 4G
      TYPE: SPIGOT
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data: {}
