version = "3.8"

[services.logseq]
image = "ghcr.io/logseq/logseq-webapp:latest"
container_name = "logseq"
hostname = "logseq"
ports = [
  "3443:443"
]
restart = "always"

[[services.logseq.volumes]]
type = "volume"
source = "certs"
target = "/etc/nginx/certs"

[[services.logseq.volumes]]
type = "volume"
source = "nginx_conf"
target = "/etc/nginx/conf.d"

[volumes.data]
[volumes.certs]
[volumes.nginx_conf]
