version = "3.8"

[services.logseq]
image = "ghcr.io/logseq/logseq-webapp:latest"
container_name = "logseq"
hostname = "logseq"
ports = [
  "3001:80"
]

# [[services.logseq.volumes]]
# type = "volume"
# source = "data"
# target  = "/data"

# [volumes.data]
