services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    security_opt:
      - no-new-privileges:true
    container_name: logseq
    hostname: logseq
    networks:
      - swag
    restart: always
    volumes:
      - type: volume
        source: certs
        target: /etc/nginx/certs
      - type: volume
        source: nginx_conf
        target: /etc/nginx/conf.d
volumes:
  certs: {}
  nginx_conf: {}
networks:
  swag:
    external: true
