[services.cloudflare-ddns]
image = "timothyjmiller/cloudflare-ddns:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "cloudflare-ddns"
network_mode = "host"
restart = "unless-stopped"
[services.cloudflare-ddns.environment]
PUID = 1000
GUID = 1000
TZ = "America/Panama"
[[services.cloudflare-ddns.volumes]]
type = "bind"
source = "/etc/localtime"
target = "/etc/localtime"
read_only = true
[[services.cloudflare-ddns.volumes]]
type = "bind"
source = "/var/lib/docker/volumes/cloudflare-ddns_data/_data/config.json"
target = "/config.json"
# [volumes]
# [volumes.data]
