[services.cloudflare-ddns]
image = "favonia/cloudflare-ddns:latest"
security_opt = [ "no-new-privileges:true" ]
container_name = "cloudflare-ddns"
network_mode = "host"
restart = "unless-stopped"
cap_add = [ "SETUID", "SETGID"]
cap_drop = [ "all" ]
read_only = true
[services.cloudflare-ddns.environment]
PUID = 1000
GUID = 1000
TZ = "America/Panama"
CF_API_TOKEN = "CFAPITOKEN"
DOMAINS = "example.org,www.example.org"
IP6_PROVIDER = "none"
PROXIED = false
