version: "3.9"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    security_opt:
      - no-new-privileges:true
    container_name: cloudflare-ddns
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: 1000
      GUID: 1000
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: /var/lib/docker/volumes/cloudflare-ddns_data/_data/config.json
        target: /config.json
